CREATE VIEW BOOKS_RS
AS
SELECT b.ISBN, b.TITLE, p.NAME as 'Publisher Name', a.FIRSTNAME + ' ' + a.LASTNAME as 'Author Name' FROM BOOKS AS b JOIN PUBLISHERS AS p ON p.ID = b.PUBLISHER_ID JOIN BOOKS_AUTHORS as ba ON ba.BOOK_ID = b.ISBN JOIN AUTHORS as a ON ba.AUTHOR_ID = a.ID