--DROP TRIGGER AUDIT_DELETE_TRIGGER_RS
CREATE TRIGGER AUDIT_DELETE_TRIGGER_RS ON PUBLISHERS FOR DELETE
AS 
BEGIN
 INSERT INTO AUDIT_MESSAGES SELECT 'DELETED PUBLISHER NAMED: ' + NAME FROM DELETED
END



