CREATE PROCEDURE InsertBookWithPublisher_RS
    @ISBN VARCHAR(20), 
    @TITLE NVARCHAR(100), 
    @PAGES SMALLINT, 
    @PRICE DECIMAL (5,2), 
    @AVAILABLE BIT, 
    @PUBLISHER_NAME VARCHAR(20) 
AS 
INSERT INTO BOOKS (ISBN, TITLE, PAGES, PRICE, AVAILABLE, PUBLISHER_ID) SELECT @ISBN, @TITLE, @PAGES, @PRICE, @AVAILABLe, ID FROM PUBLISHERS WHERE NAME=@PUBLISHER_NAME;
