DROP PROCEDURE IF EXISTS SELECT_ALL_PUBLISHERS_RS 
GO -- schließt den vorherigen Query-Block ab und startet einen neuen
CREATE PROCEDURE SELECT_ALL_PUBLISHERS_RS 
AS 
SELECT * FROM PUBLISHERS ORDER BY NAME