CREATE PROCEDURE TOP_10_PRICED_BOOKS_RS
AS 
select top (10)
    *
from (                        SELECT ISBN, TITLE, PAGES, PRICE, AVAILABLE, PUBLISHER_ID
        FROM BOOKS
    UNION
        SELECT ISBN, TITLE, PAGES, PRICE, AVAILABLE, PUBLISHER_ID
        FROM SPECIALBOOKS
    UNION
        SELECT ISBN, TITLE, PAGES, PRICE, AVAILABLE, PUBLISHER_ID
        FROM SCHOOLBOOKS 
) as allbooks
order by price DESC
