-- Anlegen der Tabelle BOOK mit Namenskürzel für den SQL Server)
DROP TABLE IF EXISTS BOOKS_SR
DROP TABLE IF EXISTS PUBLISHERS_SR
DROP TABLE IF EXISTS STORE_SR
DROP TABLE IF EXISTS LOGS_SR
CREATE TABLE BOOKS_SR (ISBN VARCHAR(20) PRIMARY KEY, TITLE NVARCHAR(100) NOT NULL, PAGES SMALLINT, PRICE DECIMAL (5,2), AVAILABLE BIT) 
CREATE TABLE PUBLISHERS_SR (ID INT PRIMARY KEY, NAME NVARCHAR(50), CITY NVARCHAR(100), STREET NVARCHAR(100))
CREATE TABLE STORE_SR (CATEGORY NVARCHAR(20), ITEM NVARCHAR(20), STOCK INT, PRIMARY KEY (CATEGORY, ITEM))
CREATE TABLE LOGS_SR (LOG_MESSAGE VARCHAR(1024))