-- Anlegen der Tabelle BOOK mit Namenskürzel für den SQL Server)
DROP TABLE IF EXISTS BOOKS_SR
DROP TABLE IF EXISTS PUBLISHERS_SR
DROP TABLE IF EXISTS STORE_SR
DROP TABLE IF EXISTS LOGS_SR

CREATE TABLE PUBLISHERS_SR (
    ID INT, 
    NAME NVARCHAR(50), 
    CITY NVARCHAR(100), 
    STREET NVARCHAR(100), 
    PRIMARY KEY (ID)
)


CREATE TABLE BOOKS_SR (
    ISBN VARCHAR(20), 
    TITLE NVARCHAR(100) NOT NULL, 
    PAGES SMALLINT CHECK (PAGES >= 0), 
    PRICE DECIMAL (5,2) CHECK (PRICE >= 0), 
    AVAILABLE BIT NOT NULL DEFAULT 0, 
    PUBLISHER_ID INT,
    PRIMARY KEY (ISBN),
    FOREIGN KEY (PUBLISHER_ID) REFERENCES PUBLISHERS_SR(ID)
) 


CREATE TABLE STORE_SR (
    CATEGORY NVARCHAR(20), 
    ITEM NVARCHAR(20), 
    STOCK INT CHECK (STOCK > 0), 
    PRIMARY KEY (CATEGORY, ITEM)
)

CREATE TABLE LOGS_SR (
    LOG_MESSAGE VARCHAR(1024)
)