-- Bücher des Autors Pausenkurt
--SELECT B.*  FROM BOOKS AS B JOIN BOOKS_AUTHORS AS BA ON B.ISBN = BA.BOOK_ID JOIN AUTHORS AS A ON BA.AUTHOR_ID = A.ID WHERE A.LASTNAME = 'Pausenkurt';
-- Addressen der Publisher
--SELECT P.ID AS PublisherId, P.NAME, A.STREET, A.CITY FROM PUBLISHERS AS P JOIN PUBLISHERS_ADDRESSES AS PA ON P.ID = PA.PUBLISHER_ID JOIN ADDRESSES AS A ON PA.ADDRESS_ID = A.ID
-- Verleger des Autors Pausenkurt
--SELECT P.NAME FROM PUBLISHERS AS P JOIN BOOKS AS B ON P.ID = B.PUBLISHER_ID JOIN BOOKS_AUTHORS AS BA ON B.ISBN = BA.BOOK_ID JOIN AUTHORS AS A ON BA.AUTHOR_ID = A.ID WHERE A.LASTNAME = 'Pausenkurt'
-- Bestseller
SELECT * FROM BOOKS AS B JOIN BOOKS_AUTHORS AS BA ON BA.BOOK_ID = B.ISBN JOIN AUTHORS AS A ON BA.AUTHOR_ID = A.ID JOIN BOOK_HAS_STATISTIC AS BHS ON BHS.BOOK_ID = B.ISBN JOIN BOOK_STATISTICS AS BS ON BHS.STATISTIC_ID = BS.ISBN WHERE BS.SOLD >= 5;