INSERT INTO PUBLISHERS_SR (ID, NAME, CITY, STREET) VALUES (1, 'Springer', 'Berlin', 'Alexanderplatz');
INSERT INTO PUBLISHERS_SR (ID, NAME, CITY, STREET) VALUES (2, 'Addison', 'New York', 'Cenrtral Park');
INSERT INTO BOOKS_SR(ISBN, TITLE, PAGES, PRICE) VALUES('ISBN1', 'Databases', 400, 9.99);
INSERT INTO BOOKS_SR(ISBN, TITLE, PAGES, PRICE, PUBLISHER_ID) VALUES('ISBN2', 'Java', 300, 19.99, 1);
INSERT INTO BOOKS_SR(ISBN, TITLE, PAGES, PRICE, PUBLISHER_ID) VALUES('ISBN3', 'C#', 500, 29.99, 1);
INSERT INTO BOOKS_SR(ISBN, TITLE, PAGES, PRICE, PUBLISHER_ID) VALUES('ISBN4', 'The Beatles', 1500, 99.99, 2);
