DELETE FROM STORE_SR
INSERT INTO STORE_SR (CATEGORY, ITEM, STOCK) VALUES ('books', 'ISBN-1', 2)
SELECT * FROM STORE_SR
-- INSERT INTO STORE_SR (CATEGORY, ITEM, STOCK) VALUES ('books', 'ISBN-2', -5)
-- INSERT INTO STORE_SR (CAT, ITEM, STOCK) VALUES ('books', 'ISBN-2', -5)
-- INSERT INTO STORE_SR (STOCK, CATEGORY, ITEM) VALUES ('books', 'ISBN-2', -5)